name: ARPs
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ main ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: configurar python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: python main.py
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Automated Change (updated message)
          commit_user_name: kiqdiaz [GitHub Actions]
          commit_user_email: lecuevad@gmail.com
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
